apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n-web-deployment
  labels:
    app: n8n-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n-web
  template:
    metadata:
      labels:
        app: n8n-web
    spec:
      containers:
        - name: execution-web
          image: ikrambagban/n8n-web:a29a91c49de2b6f3abc93ca2d71a91e7442254af
          ports:
            - containerPort: 3000
          volumeMounts:
            - name: secret
              mountPath: /app/.env
              subPath: .env
      volumes:
          - name: secret
            secret:
              secretName: n8n-web-secret
              items:
                - key: .env
                  path: .env
