apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingres-nginx
  labels:
    name: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  ingressClassName: nginx
  rules:
  - host: n8n.proxlay.com
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: n8n-web-service
            port:
              number: 80
