apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: super-ingress
  labels:
    name: ingress-nginx
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - n8n.proxlay.com
    secretName: n8n-proxlay-tls
  rules:
  - host: n8n.proxlay.com
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: n8n-web-service
            port:
              number: 80
